Repository aimclub/FEDOT, pull requests merged in 2020-12, with the labels that each got.

#188 Add PyPi publish package trigger in CI
  .github/workflows/publish_pypi.yml
  .gitignore
  MANIFEST.in
  extra_requirements.txt
  requirements.txt
  setup.py
Labels: deployment

#203 PCA feature extraction bugfix
  fedot/core/models/evaluation/data_evaluation.py
Labels: bug

#206 PyPI version update to 0.1.3
  cases/data/gapfilling/TS_temperature_gapfilling.csv
  cases/time_series_gapfilling_case.py
  examples/time_series_gapfilling_example.py
  fedot/core/composer/chain.py
  fedot/core/composer/ts_chain.py
  fedot/core/models/data.py
  fedot/core/models/evaluation/data_evaluation.py
  fedot/core/repository/data/model_repository.json
  fedot/utilities/ts_gapfilling.py
  setup.py
  test/data/test_custom_json_template.json
  test/real_applications/test_examples.py
  test/real_applications/test_real_cases.py
  test/tasks/test_gapfilling.py
Labels: release

#213 Error with tuning the non-tunable models (e.g. PCA) fixed
  fedot/core/models/evaluation/evaluation.py
  fedot/core/models/model.py
  fedot/core/models/tuning/tuners.py
  test/chain/test_chain_tuning.py
Labels: bug
