Repository aimclub/FEDOT, pull requests merged in 2020-10, with the labels that each got.

#156 The choice of the custom target implemented
  core/models/data.py
  examples/multiclass_prediction.py
  test/data/classification_with_categorical.csv
  test/data/simple_classification_with_custom_target.csv
  test/test_data.py
Labels: enhancement

#159 Enum comparison bug fixed
  core/composer/composer.py
  core/composer/optimisers/crossover.py
  core/composer/optimisers/inheritance.py
  core/composer/optimisers/mutation.py
  core/composer/optimisers/regularization.py
  core/composer/optimisers/selection.py
  core/models/evaluation/automl_eval.py
  core/repository/dataset_types.py
  core/repository/quality_metrics_repository.py
  core/repository/tasks.py
  core/utils.py
Labels: bug

#144 Implement export of the composite model structure to json #129
  core/composer/chain.py
  core/composer/node.py
  docs/source/fedot/utilities.rst
  docs/source/fedot/utilities/chain_to_json.rst
  docs/source/fedot/utilities/img/chain_to_json_main.png
  requirements.txt
  test/data/test_custom_json_template.json
  test/test_chain_import_export.py
  test/test_utils.py
  utilities/synthetic/chain_template_new.py
Labels: deployment, in progress
