Repository aimclub/FEDOT, pull requests merged in 2021-08, with the labels that each got.

#370 Sparse lagged time series transformation operation implementation
  fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
  fedot/core/operations/evaluation/time_series.py
  fedot/core/pipelines/tuning/hyperparams.py
  fedot/core/repository/data/data_operation_repository.json
  fedot/core/repository/data/default_model_params.json
  test/data/multi_modal/1951264.jpeg
  test/unit/data_operations/test_time_series_operations.py
Labels: in progress

#378 Guide for custom model implementation
  README.rst
  docs/contributing.rst
  docs/files/custom_operation_guide.pdf
  docs/source/contribution.rst
  docs/source/fedot/features/gpu_evaluation.rst
Labels: documentation

#381 Correct RANSAC operation parameters
  fedot/core/repository/data/default_model_params.json
  test/unit/data_operations/test_data_operation_params.py
Labels: bug

#382 Change logging when default tuner metric is set
  fedot/api/api_utils.py
  requirements.txt
  test/unit/api/test_api_utils.py
Labels: minor

#375 Made incremental parameters change
  examples/time_series/ts_forecasting_composing.py
  fedot/core/composer/gp_composer/specific_operators.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
  fedot/core/operations/operation.py
  fedot/core/pipelines/node.py
  fedot/core/pipelines/tuning/hyperparams.py
  test/unit/composer/test_mutation_params.py
  test/unit/data_operations/test_time_series_operations.py
Labels: enhancement, in progress

#380 Hyperparameters adaptation fix
  examples/fedot_based_solutions/graph_model_optimization.py
  examples/time_series/ts_forecasting_composing.py
  fedot/core/composer/constraint.py
  fedot/core/composer/gp_composer/gp_composer.py
  fedot/core/dag/graph_node.py
  fedot/core/dag/graph_operator.py
  fedot/core/dag/node_operator.py
  fedot/core/optimisers/adapters.py
  fedot/core/optimisers/gp_comp/gp_operators.py
  fedot/core/optimisers/gp_comp/operators/mutation.py
  fedot/core/optimisers/graph.py
  fedot/core/pipelines/node.py
  fedot/core/pipelines/validation.py
  fedot/core/pipelines/validation_rules.py
  test/unit/dag/test_graph.py
  test/unit/optimizer/test_gp_operators.py
  test/unit/tasks/test_custom.py
  test/unit/visualization/test_composing_history.py
Labels: bug, in progress

#404 Iss403
  fedot/api/help.py
  fedot/core/pipelines/tuning/hyperparams.py
  fedot/core/pipelines/tuning/search_space.py
  fedot/core/pipelines/tuning/sequential.py
  fedot/core/pipelines/tuning/tuner_interface.py
  fedot/core/pipelines/tuning/unified.py
  test/unit/pipelines/test_pipeline_tuning.py
Labels: enhancement

#408 Parameters displaying bug fix
  fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
  fedot/core/operations/operation.py
  fedot/core/pipelines/node.py
  test/unit/data_operations/test_data_operation_params.py
Labels: bug
