Repository aimclub/FEDOT, pull requests merged in 2021-11, with the labels that each got.

#487 Fix K-nn model
  fedot/core/operations/evaluation/operation_implementations/models/knn.py
  test/unit/data_operations/test_data_operations_implementations.py
Labels: bug

#478 + classes/interfaces for 'OptHistory' serialization (FEDOT.Web)
  fedot/core/dag/graph.py
  fedot/core/dag/graph_node.py
  fedot/core/dag/node_operator.py
  fedot/core/log.py
  fedot/core/operations/evaluation/evaluation_interfaces.py
  fedot/core/operations/evaluation/operation_implementations/implementation_interfaces.py
  fedot/core/operations/operation.py
  fedot/core/operations/operation_template.py
  fedot/core/optimisers/adapters.py
  fedot/core/optimisers/gp_comp/gp_optimiser.py
  fedot/core/optimisers/gp_comp/individual.py
  fedot/core/optimisers/graph.py
  fedot/core/optimisers/opt_history.py
  fedot/core/pipelines/convert.py
  fedot/core/pipelines/template.py
  fedot/core/serializers/__init__.py
  fedot/core/serializers/basic_serializer.py
  fedot/core/serializers/graph_node_serializer.py
  fedot/core/serializers/graph_serializer.py
  fedot/core/serializers/interfaces/__init__.py
  fedot/core/serializers/interfaces/serializable.py
  fedot/core/serializers/json_helpers.py
  fedot/core/serializers/operation_serializer.py
  fedot/core/serializers/pipeline_template_serializer.py
  requirements.txt
  test/unit/composer/test_history.py
  test/unit/serialization/__init__.py
  test/unit/serialization/dataclasses/serialization_dataclasses.py
  test/unit/serialization/fixtures/serialization_fixtures.py
  test/unit/serialization/mocks/serialization_mocks.py
  test/unit/serialization/shared_data.py
  test/unit/serialization/test_decoder.py
  test/unit/serialization/test_encoder.py
  test/unit/serialization/test_get_class.py
  test/unit/serialization/test_object_path_dumping.py
  test/unit/visualization/test_composing_history.py
Labels: minor

#482 Feature/pipeline explanations
  examples/interpretable/__init__.py
  examples/interpretable/api_explain.py
  examples/interpretable/pipeline_explain.py
  fedot/api/main.py
  fedot/core/composer/metrics.py
  fedot/core/pipelines/pipeline.py
  fedot/explainability/__init__.py
  fedot/explainability/explainer_template.py
  fedot/explainability/explainers.py
  fedot/explainability/surrogate_explainer.py
  test/integration/real_applications/test_examples.py
  test/unit/explainability/__init__.py
  test/unit/explainability/test_pipeline_explanation.py
Labels: enhancement, cases, test
