Repository aimclub/FEDOT, pull requests merged in 2021-12, with the labels that each got.

#484 Modifying table preprocessing
  fedot/api/api_utils/api_composer.py
  fedot/api/api_utils/api_data.py
  fedot/api/api_utils/api_utils.py
  fedot/api/api_utils/data.py
  fedot/api/api_utils/initial_assumptions.py
  fedot/api/api_utils/metrics.py
  fedot/api/api_utils/params.py
  fedot/api/api_utils/presets.py
  fedot/api/main.py
  fedot/core/data/data.py
  fedot/core/data/data_preprocessing.py
  fedot/core/data/data_split.py
  fedot/core/data/supplementary_data.py
  fedot/core/operations/atomized_template.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
  fedot/core/operations/evaluation/operation_implementations/models/discriminant_analysis.py
  fedot/core/operations/evaluation/operation_implementations/models/knn.py
  fedot/core/operations/operation_template.py
  fedot/core/pipelines/node.py
  fedot/core/pipelines/pipeline.py
  fedot/core/pipelines/template.py
  fedot/core/pipelines/tuning/tuner_interface.py
  fedot/core/repository/data/data_operation_repository.json
  fedot/core/repository/operation_types_repository.py
  fedot/core/serializers/basic_serializer.py
  fedot/core/serializers/graph_node_serializer.py
  fedot/core/serializers/graph_serializer.py
  fedot/core/serializers/json_helpers.py
  fedot/core/serializers/operation_serializer.py
  fedot/core/serializers/pipeline_template_serializer.py
  fedot/preprocessing/__init__.py
  fedot/preprocessing/categorical.py
  fedot/preprocessing/preprocessing.py
  fedot/preprocessing/structure.py
  test/unit/api/test_api_utils.py
  test/unit/api/test_main_api.py
  test/unit/data_operations/test_data_operations_implementations.py
  test/unit/models/test_atomized_model.py
  test/unit/pipelines/test_node.py
  test/unit/pipelines/test_pipeline.py
  test/unit/pipelines/test_pipeline_preprocessing.py
  test/unit/pipelines/test_pipeline_structure.py
  test/unit/remote/test_remote_composer.py
  test/unit/test_data_preprocessing.py
  test/unit/utilities/test_pipeline_import_export.py
Labels: bug, enhancement, in progress

#508 Improving binary feature processing
  fedot/api/main.py
  fedot/core/data/data_preprocessing.py
  fedot/core/operations/evaluation/evaluation_interfaces.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
  test/unit/api/test_main_api.py
  test/unit/data_operations/test_data_operations_implementations.py
  test/unit/test_data_preprocessing.py
Labels: enhancement

#512 Implement Label Encoder
  fedot/core/operations/evaluation/common_preprocessing.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/categorical_encoders.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
  fedot/core/repository/data/data_operation_repository.json
  fedot/preprocessing/preprocessing.py
  test/unit/data_operations/test_data_operations_implementations.py
  test/unit/models/test_model.py
Labels: enhancement, core

#514 Safe mode implementation
  fedot/api/api_utils/api_data.py
  fedot/api/api_utils/api_data_analyser.py
  fedot/api/api_utils/params.py
  fedot/api/api_utils/presets.py
  fedot/api/main.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/categorical_encoders.py
  fedot/core/repository/data/model_repository.json
  fedot/preprocessing/preprocessing.py
  test/unit/api/test_api_safety.py
Labels: in progress

#515 Types processing system implemented
  fedot/api/api_utils/api_data.py
  fedot/api/api_utils/api_data_analyser.py
  fedot/api/api_utils/params.py
  fedot/api/main.py
  fedot/core/data/data.py
  fedot/core/data/data_preprocessing.py
  fedot/core/data/data_split.py
  fedot/core/data/merge.py
  fedot/core/data/supplementary_data.py
  fedot/core/operations/atomized_model.py
  fedot/core/operations/data_operation.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/categorical_encoders.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/text_preprocessing.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
  fedot/core/operations/evaluation/operation_implementations/implementation_interfaces.py
  fedot/core/operations/evaluation/operation_implementations/models/discriminant_analysis.py
  fedot/core/operations/model.py
  fedot/core/operations/operation.py
  fedot/core/pipelines/pipeline.py
  fedot/core/pipelines/tuning/search_space.py
  fedot/core/repository/data/model_repository.json
  fedot/core/utils.py
  fedot/preprocessing/categorical.py
  fedot/preprocessing/data_types.py
  fedot/preprocessing/preprocessing.py
  test/data/scoring/scoring_test.csv
  test/data/scoring/scoring_train.csv
  test/unit/api/test_api_safety.py
  test/unit/api/test_api_utils.py
  test/unit/api/test_main_api.py
  test/unit/data/test_data_merge.py
  test/unit/data_operations/test_data_operations_implementations.py
  test/unit/models/test_atomized_model.py
  test/unit/models/test_model.py
  test/unit/pipelines/test_decompose_pipelines.py
  test/unit/pipelines/test_pipeline.py
  test/unit/preprocessing/__init__.py
  test/unit/preprocessing/test_pipeline_preprocessing.py
  test/unit/preprocessing/test_preprocessing_though_api.py
  test/unit/preprocessing/test_preprocessors.py
  test/unit/tasks/test_classification.py
  test/unit/tasks/test_regression.py
  test/unit/test_logger.py
  test/unit/utilities/test_pipeline_import_export.py
Labels: in progress, discuss

#521 Simplifying the tests
  examples/advanced/gpu_example.py
  examples/advanced/pipeline_sensitivity.py
  examples/advanced/time_series_forecasting/composing_pipelines.py
  examples/advanced/time_series_forecasting/multistep.py
  examples/advanced/time_series_forecasting/sparse_lagged_tuning.py
  examples/simple/classification/classification_pipelines.py
  examples/simple/classification/classification_with_tuning.py
  examples/simple/classification/resample_example.py
  examples/simple/pipeline_and_history_visualisation.py
  examples/simple/pipeline_import_export.py
  examples/simple/pipeline_log.py
  examples/simple/pipeline_tune.py
  examples/simple/regression/regression_pipelines.py
  examples/simple/regression/regression_with_tuning.py
  examples/simple/time_series_forecasting/ts_pipelines.py
  examples/simple/time_series_forecasting/tuning_pipelines.py
  test/data/classification_with_categorical.csv
  test/data/multi_target_sample.csv
  test/data/simple_sea_level.csv
  test/integration/real_applications/test_examples.py
  test/integration/test_automl.py
  test/unit/api/test_main_api.py
  test/unit/composer/test_composer.py
  test/unit/data/test_data.py
  test/unit/models/test_custom_model_introduction.py
  test/unit/pipelines/test_pipeline_tuning.py
  test/unit/tasks/test_classification.py
Labels: test

#518 Target from InputData in predict mode should be ignored in (almost) all cases
  fedot/core/data/data.py
  fedot/core/operations/evaluation/operation_implementations/models/keras.py
  fedot/core/pipelines/pipeline.py
  test/unit/api/test_main_api.py
  test/unit/common_tests.py
  test/unit/models/test_model.py
  test/unit/tasks/test_classification.py
  test/unit/tasks/test_regression.py
Labels: bug, question, in progress, test

#520 External optimizer support added
  cases/credit_scoring/credit_scoring_problem_multiobj.py
  cases/multi_modal_rating_prediction.py
  cases/river_levels_prediction/river_level_case_composer.py
  examples/advanced/fedot_based_solutions/external_optimizer.py
  examples/advanced/fedot_based_solutions/graph_model_optimization.py
  examples/advanced/pipeline_sensitivity.py
  examples/advanced/sensitivity_analysis/pipelines_access.py
  examples/advanced/time_series_forecasting/composing_pipelines.py
  examples/simple/classification/multiclass_prediction.py
  examples/simple/pipeline_and_history_visualisation.py
  fedot/api/api_utils/api_composer.py
  fedot/core/composer/composer.py
  fedot/core/composer/composer_builder.py
  fedot/core/composer/gp_composer/fixed_structure_composer.py
  fedot/core/composer/gp_composer/gp_composer.py
  fedot/core/optimisers/gp_comp/gp_optimiser.py
  fedot/core/optimisers/gp_comp/operators/crossover.py
  fedot/core/optimisers/gp_comp/operators/mutation.py
  fedot/core/optimisers/gp_comp/operators/regularization.py
  fedot/core/optimisers/gp_comp/operators/selection.py
  fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
  fedot/core/optimisers/graph.py
  fedot/core/optimisers/optimizer.py
  fedot/core/optimisers/timer.py
  test/unit/composer/test_builder.py
  test/unit/composer/test_composer.py
  test/unit/dag/test_node_operator.py
  test/unit/optimizer/test_external.py
  test/unit/optimizer/test_gp_operators.py
  test/unit/optimizer/test_selection_operators.py
  test/unit/optimizer/test_timer.py
  test/unit/preprocessing/test_preprocessing_though_api.py
  test/unit/tasks/test_custom.py
  test/unit/validation/test_table_cv.py
  test/unit/validation/test_time_series_cv.py
Labels: enhancement, refactoring, composer

#527 Improvement of time series processing
  fedot/core/data/merge.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
  fedot/preprocessing/data_types.py
  test/unit/data_operations/test_data_operations_implementations.py
  test/unit/pipelines/test_pipeline.py
  test/unit/tasks/test_forecasting.py
Labels: bug, enhancement
