Repository aimclub/FEDOT, pull requests merged in 2021-07, with the labels that each got.

#283 Example of additional learning using atomization
  examples/additional_learning.py
  fedot/api/api_utils.py
  fedot/core/operations/atomized_model.py
  fedot/core/pipelines/pipeline.py
  fedot/core/pipelines/validation_rules.py
  test/unit/models/test_atomized_model.py
Labels: cases, core

#360 Notebooks replacement
  README.rst
  examples/additional_learning.py
  examples/data/salaries.csv
  examples/data/ts_sea_level.csv
  examples/fedot_api_example.py
  examples/ts_forecasting_tuning.py
  examples/ts_forecasting_with_exogenous.py
  examples/ts_multistep_example.py
  notebooks/README.md
  notebooks/data/scoring_test.csv
  notebooks/data/scoring_train.csv
  notebooks/data/ts_traffic.csv
  notebooks/jupyter_media/fedot_structure/fedot_structure_02.png
  notebooks/jupyter_media/fedot_structure/fedot_structure_03.png
  notebooks/jupyter_media/fedot_structure/logit_qda_lda.png
  notebooks/jupyter_media/fedot_structure/logit_scaling_lda.png
  notebooks/jupyter_media/fedot_structure/model_node_chain.png
  notebooks/jupyter_media/fedot_structure/operation_node_chain.png
  notebooks/jupyter_media/models/April-26-2021,19-25-09,PM/.json
  notebooks/jupyter_media/models/April-26-2021,19-25-09,PM/fitted_operations/operation_0.pkl
  notebooks/jupyter_media/models/April-26-2021,19-25-09,PM/fitted_operations/operation_1.pkl
  notebooks/jupyter_media/models/April-26-2021,19-25-09,PM/fitted_operations/operation_2.pkl
  notebooks/jupyter_media/models/April-26-2021,19-25-09,PM/fitted_operations/operation_3.pkl
  notebooks/jupyter_media/models/April-26-2021,19-25-09,PM/fitted_operations/operation_4.pkl
  notebooks/jupyter_media/models/April-26-2021,19-25-09,PM/fitted_operations/operation_5.pkl
  notebooks/jupyter_media/models/April-26-2021,19-25-09,PM/fitted_operations/operation_6.pkl
  notebooks/jupyter_media/time_series/animation_forecast.gif
  notebooks/jupyter_media/time_series/autoregressive_models.png
  notebooks/jupyter_media/time_series/batch_approximation.gif
  notebooks/jupyter_media/time_series/chain_tuning.gif
  notebooks/jupyter_media/time_series/chains_example.png
  notebooks/jupyter_media/time_series/data_flow.png
  notebooks/jupyter_media/time_series/iterative_approximation.gif
  notebooks/jupyter_media/time_series/multi_lagged_chain.png
  notebooks/jupyter_media/time_series/sea_map.png
  notebooks/jupyter_media/time_series/sequental_tuning.gif
  notebooks/jupyter_media/time_series/time_series_simple.png
  notebooks/jupyter_media/time_series/trend_and_resid.png
  notebooks/jupyter_media/time_series/ts_gapfilling.png
  notebooks/jupyter_media/time_series/window_sizes.png
  notebooks/latest/1_intro_to_automl.ipynb
  notebooks/latest/2_intro_to_fedot.ipynb
  notebooks/latest/3_intro_ts_forecasting.ipynb
  notebooks/latest/4_auto_ts_forecasting.ipynb
  notebooks/latest/5_ts_specific_cases.ipynb
  notebooks/version_02_1/1_intro_to_automl.ipynb
  notebooks/version_02_1/2_intro_to_fedot.ipynb
  notebooks/version_02_1/3_intro_ts_forecasting.ipynb
  notebooks/version_03/1_intro_to_automl.ipynb
  notebooks/version_03/2_intro_to_fedot.ipynb
  notebooks/version_03/3_intro_ts_forecasting.ipynb
  notebooks/version_03/4_auto_ts_forecasting.ipynb
  notebooks/version_03/5_ts_specific_cases.ipynb
Labels: documentation

#356 catboost default params changed
  fedot/core/operations/evaluation/evaluation_interfaces.py
  fedot/core/operations/operation.py
Labels: bug

#363 Cross validation methods for time series
  cases/data/time_series/temperature.csv
  cases/data/time_series/traffic.csv
  examples/additional_learning.py
  examples/ts_forecasting_composing.py
  examples/ts_forecasting_tuning.py
  fedot/api/api_utils.py
  fedot/api/main.py
  fedot/core/composer/composer.py
  fedot/core/composer/constraint.py
  fedot/core/composer/gp_composer/gp_composer.py
  fedot/core/composer/metrics.py
  fedot/core/data/data_split.py
  fedot/core/data/supplementary_data.py
  fedot/core/operations/cross_validation.py
  fedot/core/operations/evaluation/evaluation_interfaces.py
  fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
  fedot/core/pipelines/pipeline.py
  fedot/core/pipelines/ts_wrappers.py
  fedot/core/pipelines/tuning/hyperparams.py
  fedot/core/pipelines/tuning/sequential.py
  fedot/core/pipelines/tuning/tuner_interface.py
  fedot/core/pipelines/tuning/unified.py
  fedot/core/pipelines/validation.py
  fedot/core/repository/quality_metrics_repository.py
  fedot/core/validation/compose/__init__.py
  fedot/core/validation/compose/metric_estimation.py
  fedot/core/validation/compose/tabular.py
  fedot/core/validation/compose/time_series.py
  fedot/core/validation/split.py
  fedot/core/validation/tune/__init__.py
  fedot/core/validation/tune/simple.py
  fedot/core/validation/tune/time_series.py
  fedot/sensitivity/node_sa_approaches.py
  test/data/multi_modal/1951264.jpeg
  test/data/multi_modal/1951265.jpeg
  test/unit/api/test_main_api.py
  test/unit/composer/test_quality_metrics.py
  test/unit/pipelines/test_pipeline_ts_wrappers.py
  test/unit/pipelines/test_pipeline_validation.py
  test/unit/tasks/test_regression.py
  test/unit/validation/__init__.py
  test/unit/validation/test_table_cv.py
  test/unit/validation/test_time_series_cv.py
Labels: enhancement

#327 Prototype of GPU evaluation
  Dockerfile
  cases/credit_scoring/credit_scoring_problem.py
  cases/credit_scoring/credit_scoring_problem_multiobj.py
  cases/multi_modal_rating_prediction.py
  docs/source/fedot/features/gpu_evaluation.rst
  examples/gpu_example.py
  examples/pipeline_from_automl.py
  examples/pipeline_sensitivity.py
  examples/sensitivity_analysis/pipelines_access.py
  fedot/api/api_utils.py
  fedot/api/help.py
  fedot/core/composer/gp_composer/gp_composer.py
  fedot/core/operations/data_operation.py
  fedot/core/operations/evaluation/classification.py
  fedot/core/operations/evaluation/evaluation_interfaces.py
  fedot/core/operations/evaluation/gpu/__init__.py
  fedot/core/operations/evaluation/gpu/classification.py
  fedot/core/operations/evaluation/gpu/clustering.py
  fedot/core/operations/evaluation/gpu/common.py
  fedot/core/operations/evaluation/gpu/regression.py
  fedot/core/operations/factory.py
  fedot/core/operations/model.py
  fedot/core/operations/operation.py
  fedot/core/pipelines/node.py
  fedot/core/pipelines/pipeline.py
  fedot/core/pipelines/validation_rules.py
  fedot/core/repository/data/automl_repository.json
  fedot/core/repository/data/gpu_models_repository.json
  fedot/core/repository/operation_types_repository.py
  fedot/sensitivity/node_sa_approaches.py
  gpu/Dockerfile
  gpu/conda_gpu_requirements.sh
  test/integration/test_automl.py
  test/test_gpu_strategy.py
  test/unit/api/test_api_info.py
  test/unit/models/test_repository.py
Labels: core, in progress

#371 Hotfix tuner and test
  fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
  fedot/core/pipelines/tuning/sequential.py
  fedot/core/pipelines/tuning/tuner_interface.py
  fedot/core/pipelines/tuning/unified.py
  fedot/core/repository/data/default_model_params.json
  test/data/simple_time_series.csv
  test/data/simple_time_series_test.csv
  test/unit/api/test_main_api.py
  test/unit/models/test_model.py
  test/unit/pipelines/test_decompose_pipelines.py
  test/unit/pipelines/test_pipeline_tuning.py
  test/unit/tasks/test_forecasting.py
  test/unit/utilities/test_pipeline_import_export.py
  test/unit/validation/test_time_series_cv.py
Labels: bug
