Repository aimclub/FEDOT, pull requests merged in 2022-10, with the labels that each got.

#876 Redesign Adapter subsystem
  examples/advanced/fedot_based_solutions/external_optimizer.py
  examples/advanced/fedot_based_solutions/graph_model_optimization.py
  fedot/api/api_utils/api_composer.py
  fedot/core/adapter/__init__.py
  fedot/core/adapter/adapt_registry.py
  fedot/core/adapter/adapter.py
  fedot/core/composer/gp_composer/specific_operators.py
  fedot/core/dag/graph.py
  fedot/core/dag/graph_delegate.py
  fedot/core/dag/graph_operator.py
  fedot/core/dag/graph_verifier.py
  fedot/core/dag/verification_rules.py
  fedot/core/optimisers/adapters.py
  fedot/core/optimisers/gp_comp/evaluation.py
  fedot/core/optimisers/gp_comp/gp_operators.py
  fedot/core/optimisers/gp_comp/gp_optimizer.py
  fedot/core/optimisers/gp_comp/operators/crossover.py
  fedot/core/optimisers/gp_comp/operators/mutation.py
  fedot/core/optimisers/gp_comp/operators/regularization.py
  fedot/core/optimisers/gp_comp/pipeline_composer_requirements.py
  fedot/core/optimisers/graph.py
  fedot/core/optimisers/initial_graphs_generator.py
  fedot/core/optimisers/opt_history.py
  fedot/core/optimisers/optimizer.py
  fedot/core/optimisers/populational_optimizer.py
  fedot/core/pipelines/pipeline.py
  fedot/core/pipelines/verification.py
  fedot/core/pipelines/verification_rules.py
  fedot/remote/remote_evaluator.py
  fedot/remote/run_pipeline.py
  test/conftest.py
  test/unit/adapter/__init__.py
  test/unit/adapter/mock_adapter.py
  test/unit/adapter/test_adapt_pipeline.py
  test/unit/adapter/test_adapt_registry.py
  test/unit/adapter/test_adapt_verification_rules.py
  test/unit/api/test_api_utils.py
  test/unit/composer/test_composer.py
  test/unit/dag/test_graph_utils.py
  test/unit/dag/test_node.py
  test/unit/optimizer/test_initial_population_generator.py
  test/unit/pipelines/test_pipeline_verification.py
  test/unit/tasks/test_custom.py
  test/unit/test_logger.py
Labels: refactoring, composer, architecture

#924 Fixes for long-term runs
  fedot/api/api_utils/api_composer.py
  fedot/api/api_utils/params.py
  fedot/core/constants.py
  fedot/core/optimisers/composer_requirements.py
  fedot/core/optimisers/gp_comp/gp_optimizer.py
  fedot/core/optimisers/populational_optimizer.py
  fedot/core/pipelines/tuning/tuner_builder.py
  fedot/core/utilities/grouped_condition.py
  requirements.txt
Labels: bug

#919 GraphNode interface abstraction & Graph refactorings
  examples/advanced/fedot_based_solutions/graph_model_optimization.py
  fedot/core/dag/graph.py
  fedot/core/dag/graph_delegate.py
  fedot/core/dag/graph_node.py
  fedot/core/dag/graph_utils.py
  fedot/core/dag/linked_graph.py
  fedot/core/dag/linked_graph_node.py
  fedot/core/operations/operation.py
  fedot/core/optimisers/adapters.py
  fedot/core/optimisers/gp_comp/gp_operators.py
  fedot/core/optimisers/gp_comp/operators/crossover.py
  fedot/core/optimisers/gp_comp/operators/mutation.py
  fedot/core/optimisers/gp_comp/operators/regularization.py
  fedot/core/optimisers/graph.py
  fedot/core/pipelines/convert.py
  fedot/core/pipelines/node.py
  fedot/core/pipelines/pipeline.py
  fedot/core/pipelines/pipeline_builder.py
  fedot/core/serializers/coders/graph_node_serialization.py
  fedot/core/serializers/coders/graph_serialization.py
  fedot/core/serializers/serializer.py
  fedot/core/visualisation/graph_viz.py
  fedot/sensitivity/nodes_sensitivity.py
  test/data/remote/remote_config_ts
  test/data/remote/remote_config_ts_multivar
  test/unit/dag/test_graph.py
  test/unit/dag/test_graph_operator.py
  test/unit/dag/test_node.py
  test/unit/optimizer/test_gp_operators.py
  test/unit/pipelines/test_node.py
  test/unit/pipelines/test_pipeline.py
  test/unit/tasks/test_custom.py
  test/unit/visualization/test_graph_visualizations.py
  test/unit/visualization/test_visualisation_utils.py
Labels: core, refactoring

#951 Visualizations hotfixes
  fedot/core/dag/graph.py
  fedot/core/visualisation/graph_viz.py
  fedot/core/visualisation/opt_history/fitness_box.py
  fedot/core/visualisation/opt_history/fitness_line.py
  fedot/core/visualisation/opt_history/operations_animated_bar.py
  fedot/core/visualisation/opt_history/operations_kde.py
  fedot/core/visualisation/opt_history/utils.py
Labels: bug, enhancement, minor

#941 Refactor PipelineAdapter (don't overwrite `__class__`)
  fedot/core/adapter/__init__.py
  fedot/core/adapter/adapter.py
  fedot/core/dag/graph.py
  fedot/core/dag/graph_delegate.py
  fedot/core/dag/graph_utils.py
  fedot/core/dag/graph_verifier.py
  fedot/core/dag/linked_graph.py
  fedot/core/optimisers/adapters.py
  fedot/core/optimisers/graph.py
  fedot/core/optimisers/optimizer.py
  fedot/core/serializers/serializer.py
  test/unit/adapter/test_adapt_pipeline.py
Labels: core, refactoring

#963 Optimizer separation fixes: isolate remote evaluator access
  examples/advanced/fedot_based_solutions/external_optimizer.py
  fedot/api/main.py
  fedot/core/composer/composer_builder.py
  fedot/core/optimisers/gp_comp/evaluation.py
  fedot/core/optimisers/objective/data_source_splitter.py
  fedot/core/optimisers/optimizer.py
  fedot/core/optimisers/populational_optimizer.py
  fedot/remote/remote_evaluator.py
  test/unit/optimizer/gp_operators/test_gp_operators.py
  test/unit/optimizer/test_evaluation.py
Labels: refactoring, infrastructure, architecture

#962 OptHistory returns to GraphOptimizer
  fedot/api/api_utils/api_composer.py
  fedot/core/composer/composer.py
  fedot/core/composer/composer_builder.py
  fedot/core/composer/gp_composer/gp_composer.py
  fedot/core/optimisers/composer_requirements.py
  fedot/core/optimisers/opt_history_objects/opt_history.py
  fedot/core/optimisers/optimizer.py
  fedot/core/optimisers/populational_optimizer.py
  fedot/core/visualisation/opt_viz_extra.py
  test/unit/composer/test_composer.py
  test/unit/composer/test_history.py
  test/unit/visualization/test_composing_history.py
Labels: refactoring, infrastructure
