Repository aimclub/FEDOT, pull requests merged in 2022-03, with the labels that each got.

#586 OS-independent paths in serialization
  fedot/core/operations/operation_template.py
  fedot/core/pipelines/template.py
Labels: enhancement

#553 Implemented parallelization
  examples/advanced/parallelization_comparison.py
  examples/simple/time_series_forecasting/api_foresacting.py
  fedot/api/api_utils/api_composer.py
  fedot/api/main.py
  fedot/core/composer/gp_composer/gp_composer.py
  fedot/core/optimisers/gp_comp/evaluating.py
  fedot/core/optimisers/gp_comp/gp_operators.py
  fedot/core/optimisers/gp_comp/gp_optimiser.py
  fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
  fedot/core/optimisers/optimizer.py
  fedot/core/pipelines/pipeline.py
  fedot/core/validation/compose/tabular.py
  test/unit/api/test_api_utils.py
  test/unit/composer/test_composer.py
  test/unit/pipelines/test_pipeline.py
Labels: in progress

#587 Timeouts api refactor
  examples/simple/regression/api_regression.py
  fedot/api/api_utils/api_composer.py
  fedot/api/api_utils/initial_assumptions.py
  fedot/api/api_utils/params.py
  fedot/api/main.py
  fedot/api/time.py
  fedot/core/constants.py
  fedot/core/dag/adapters.py
  fedot/core/repository/data/model_repository.json
  fedot/core/validation/tune/tabular.py
  fedot/remote/remote_evaluator.py
  fedot/utilities/pattern_wrappers.py
  test/data/pipeline_with_old_paths/fitted_operations/operation_0.pkl
  test/data/pipeline_with_old_paths/fitted_operations/operation_1.pkl
  test/data/pipeline_with_old_paths/pipeline_with_old_paths.json
  test/data/pipeline_with_old_paths/preprocessing/data_preprocessor.pkl
  test/unit/optimizer/test_external.py
  test/unit/utilities/test_pipeline_import_export.py
  test/unit/validation/test_table_cv.py
Labels: refactoring

#593 Serialization logic modified
  fedot/api/api_utils/params.py
  fedot/core/composer/gp_composer/gp_composer.py
  fedot/core/dag/graph.py
  fedot/core/dag/graph_node.py
  fedot/core/optimisers/adapters.py
  fedot/core/optimisers/gp_comp/gp_operators.py
  fedot/core/optimisers/gp_comp/gp_optimiser.py
  fedot/core/optimisers/gp_comp/individual.py
  fedot/core/optimisers/gp_comp/operators/crossover.py
  fedot/core/optimisers/gp_comp/operators/mutation.py
  fedot/core/optimisers/gp_comp/operators/regularization.py
  fedot/core/optimisers/gp_comp/operators/selection.py
  fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
  fedot/core/optimisers/graph.py
  fedot/core/optimisers/opt_history.py
  fedot/core/optimisers/optimizer.py
  fedot/core/pipelines/template.py
  fedot/core/serializers/coders/graph_node_serialization.py
  fedot/core/serializers/coders/graph_serialization.py
  fedot/core/serializers/coders/opt_history_serialization.py
  fedot/core/serializers/coders/parent_operator_serialization.py
  fedot/core/serializers/serializer.py
  test/unit/composer/test_history.py
  test/unit/dag/test_graph.py
  test/unit/models/test_atomized_model.py
  test/unit/pipelines/test_pipeline.py
  test/unit/serialization/conftest.py
  test/unit/serialization/fixtures/__init__.py
  test/unit/serialization/mocks/serialization_mocks.py
  test/unit/serialization/test_decoder.py
  test/unit/serialization/test_encoder.py
Labels: core

#606 Forbid duplicate edges in the Graph
  fedot/core/composer/advisor.py
  fedot/core/dag/graph_node.py
  fedot/core/dag/graph_operator.py
  fedot/core/optimisers/gp_comp/operators/crossover.py
  fedot/core/optimisers/gp_comp/operators/inheritance.py
  fedot/core/optimisers/gp_comp/operators/mutation.py
  fedot/core/optimisers/gp_comp/operators/regularization.py
  fedot/core/optimisers/gp_comp/operators/selection.py
  fedot/core/optimisers/graph.py
  fedot/core/repository/dataset_types.py
  fedot/core/repository/quality_metrics_repository.py
  fedot/core/repository/tasks.py
  fedot/core/serializers/coders/graph_node_serialization.py
  fedot/core/serializers/serializer.py
  fedot/core/utilities/__init__.py
  fedot/core/utilities/data_structures.py
  fedot/core/utils.py
  test/unit/dag/test_graph.py
  test/unit/dag/test_graph_operator.py
  test/unit/dag/test_unique_list.py
  test/unit/pipelines/test_node_cache.py
  test/unit/serialization/mocks/serialization_mocks.py
  test/unit/serialization/test_encoder.py
Labels: invalid, core
