Repository aimclub/FEDOT, pull requests merged in 2022-08, with the labels that each got.

#802 Simplify pickle-serialization of DataPreprocessor
  fedot/core/optimisers/gp_comp/operators/crossover.py
  fedot/preprocessing/preprocessing.py
  fedot/preprocessing/structure.py
  test/unit/optimizer/test_gp_operators.py
Labels: refactoring

#813 Minor ComposerBuilder fixes for NAS
  cases/credit_scoring/credit_scoring_problem_multiobj.py
  fedot/core/composer/composer_builder.py
  fedot/core/composer/gp_composer/gp_composer.py
  fedot/core/data/data.py
  fedot/core/optimisers/objective/__init__.py
  fedot/core/optimisers/objective/data_source_splitter.py
  fedot/core/optimisers/opt_history.py
  fedot/core/optimisers/opt_node_factory.py
  fedot/core/optimisers/optimizer.py
  fedot/core/pipelines/pipeline_graph_generation_params.py
  fedot/preprocessing/preprocessing.py
  test/unit/composer/test_composer.py
  test/unit/composer/test_history.py
  test/unit/data/test_data_split.py
  test/unit/optimizer/test_gp_operators.py
Labels: infrastructure

#820 790 fix - Resample's dimensions error
  fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
  fedot/core/repository/data/default_operation_params.json
  test/unit/data_operations/test_data_operations_implementations.py
Labels: bug

#839 Hotfix for refactoring-preprocessing
  fedot/core/optimisers/objective/data_objective_eval.py
Labels: bug

#841 Refactor visualizations
  cases/credit_scoring/credit_scoring_problem_multiobj.py
  examples/simple/pipeline_and_history_visualization.py
  fedot/api/main.py
  fedot/core/optimisers/opt_history.py
  fedot/core/visualisation/graph_viz.py
  fedot/core/visualisation/opt_history/__init__.py
  fedot/core/visualisation/opt_history/arg_constraint_wrapper.py
  fedot/core/visualisation/opt_history/fitness_box.py
  fedot/core/visualisation/opt_history/fitness_line.py
  fedot/core/visualisation/opt_history/history_visualization.py
  fedot/core/visualisation/opt_history/operations_animated_bar.py
  fedot/core/visualisation/opt_history/operations_kde.py
  fedot/core/visualisation/opt_history/utils.py
  fedot/core/visualisation/opt_viz.py
  fedot/core/visualisation/opt_viz_extra.py
  test/unit/visualization/test_visualisation_utils.py
Labels: refactoring, in progress
