Repository aimclub/FEDOT, pull requests merged in 2022-04, with the labels that each got.

#621 Refactor existing DataMerge functionality (closes #610)
  cases/multi_modal_genre_prediction.py
  fedot/api/api_utils/data_definition.py
  fedot/core/data/array_utilities.py
  fedot/core/data/data.py
  fedot/core/data/merge.py
  fedot/core/data/merge/data_merger.py
  fedot/core/data/merge/supplementary_data_merger.py
  fedot/core/data/supplementary_data.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/decompose.py
  fedot/core/pipelines/node.py
  fedot/core/pipelines/pipeline_builder.py
  fedot/core/utilities/data_structures.py
  test/unit/api/test_main_api.py
  test/unit/composer/test_quality_metrics.py
  test/unit/data/test_data.py
  test/unit/data/test_data_merge.py
  test/unit/data/test_data_merge_image.py
  test/unit/data/test_data_merge_multi_ts.py
  test/unit/data/test_data_merge_text.py
  test/unit/data/test_data_merge_ts.py
  test/unit/data/test_supplementary_data.py
  test/unit/data_operations/test_data_operations_implementations.py
  test/unit/test_logger.py
Labels: core, refactoring

#629 Mixed types columns processing improvement
  fedot/api/api_utils/api_data.py
  fedot/preprocessing/data_types.py
  test/data/data_with_mixed_column.csv
  test/unit/preprocessing/test_preprocessors.py
  test/unit/utilities/test_pipeline_import_export.py
Labels: enhancement

#642 Prototype example of multitask
  examples/data/test_synthetic_regression_classification.csv
  examples/data/train_synthetic_regression_classification.csv
  examples/multitask_classification_regression.py
  test/unit/tasks/test_multi_task.py
Labels: cases

#639 Refactoring of evaluate individuals in optimiser
  examples/advanced/fedot_based_solutions/external_optimizer.py
  fedot/api/main.py
  fedot/core/composer/composer.py
  fedot/core/composer/composer_builder.py
  fedot/core/composer/gp_composer/gp_composer.py
  fedot/core/composer/metrics.py
  fedot/core/optimisers/adapters.py
  fedot/core/optimisers/gp_comp/evaluating.py
  fedot/core/optimisers/gp_comp/gp_operators.py
  fedot/core/optimisers/gp_comp/gp_optimiser.py
  fedot/core/optimisers/gp_comp/operators/evaluation.py
  fedot/core/optimisers/gp_comp/operators/operator.py
  fedot/core/optimisers/gp_comp/operators/regularization.py
  fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
  fedot/core/optimisers/optimizer.py
  fedot/core/optimisers/timer.py
  fedot/core/pipelines/node.py
  fedot/core/repository/quality_metrics_repository.py
  fedot/core/validation/metric_estimation.py
  test/unit/composer/test_composer.py
  test/unit/composer/test_history.py
  test/unit/optimizer/test_external.py
  test/unit/optimizer/test_gp_operators.py
  test/unit/validation/test_table_cv.py
Labels: core, composer

#653 hotfix multiprocessing in evaluate
  fedot/core/optimisers/gp_comp/operators/evaluation.py
Labels: bug
