Repository aimclub/FEDOT, pull requests merged in 2022-11, with the labels that each got.

#764 Fix integration tests
  cases/credit_scoring/credit_scoring_problem.py
  cases/credit_scoring/credit_scoring_problem_multiobj.py
  cases/metocean_forecasting_problem.py
  docs/source/api/profiler.rst
  examples/advanced/automl/h2o_example.py
  examples/advanced/fedot_profiler_example.py
  examples/advanced/multi_modal_pipeline.py
  examples/advanced/multimodal_text_num_example.py
  examples/advanced/multiobj_optimisation.py
  examples/advanced/sensitivity_analysis/complex_analysis_with_requirements.py
  examples/advanced/sensitivity_analysis/mta_example.py
  examples/advanced/time_series_forecasting/exogenous.py
  examples/advanced/time_series_forecasting/multistep.py
  examples/advanced/time_series_forecasting/nemo_multiple.py
  examples/advanced/time_series_forecasting/sparse_lagged_tuning.py
  examples/simple/classification/api_classification.py
  examples/simple/interpretable/api_explain.py
  examples/simple/interpretable/pipeline_explain.py
  examples/simple/pipeline_and_history_visualization.py
  examples/simple/pipeline_log.py
  examples/simple/regression/api_regression.py
  examples/simple/time_series_forecasting/api_forecasting.py
  examples/simple/time_series_forecasting/gapfilling.py
  examples/simple/time_series_forecasting/tuning_pipelines.py
  fedot/api/main.py
  fedot/core/data/data.py
  fedot/core/repository/operation_types_repository.py
  fedot/explainability/explainers.py
  fedot/explainability/surrogate_explainer.py
  fedot/sensitivity/deletion_methods/multi_times_analysis.py
  fedot/sensitivity/node_sa_approaches.py
  fedot/sensitivity/nodes_sensitivity.py
  fedot/sensitivity/sa_requirements.py
  fedot/utilities/profiler/automl_memory_profiler.py
  test/data/simple_sea_level.csv
  test/data/spam_detection.csv
  test/integration/api_params/test_main_api_params.py
  test/integration/automl/__init__.py
  test/integration/automl/test_automl.py
  test/integration/multiprocessing/test_history.py
  test/integration/quality/test_quality_improvement.py
  test/integration/quality/test_synthetic_tasks.py
  test/integration/real_applications/test_examples.py
  test/integration/real_applications/test_real_cases.py
  test/integration/test_profiler.py
  test/unit/explainability/test_pipeline_explanation.py
  test/unit/models/test_custom_model_introduction.py
  test/unit/preprocessing/test_preprocessing_though_api.py
Labels: bug, in progress

#937 Docs & diagrams for architecture & adapter subsystem (#886)
  docs/source/advanced/adapter.rst
  docs/source/advanced/architecture.rst
  docs/source/advanced/img/NodeDeletionAnalyze.jpg
  docs/source/advanced/img/NodeReplaceModelAnalyze.jpg
  docs/source/advanced/img/adapter-structure-v1.png
  docs/source/advanced/img/knn_id_0_replacement.jpg
  docs/source/advanced/img/qda_id_1_replacement.jpg
  docs/source/advanced/img/structure-v2.png
  docs/source/advanced/index.rst
  docs/source/advanced/sensitivity_analysis.rst
  docs/source/api/adapter.rst
  docs/source/api/index.rst
  fedot/core/adapter/adapt_registry.py
  fedot/core/adapter/adapter.py
Labels: documentation

#964 Documentation for tabular data
  docs/source/basics/img_utilities/pipeline_example.png
  docs/source/basics/tabular_data.rst
Labels: documentation

#968 Documentation for `Examples and notebooks`
  docs/source/examples/index.rst
  docs/source/examples/notebooks.rst
Labels: documentation

#913 Implement custom class for generations
  fedot/api/api_utils/api_composer.py
  fedot/core/optimisers/gp_comp/gp_optimizer.py
  fedot/core/optimisers/opt_history_objects/generation.py
  fedot/core/optimisers/opt_history_objects/opt_history.py
  fedot/core/optimisers/populational_optimizer.py
  fedot/core/serializers/coders/opt_history_serialization.py
  fedot/core/serializers/serializer.py
  test/unit/composer/test_composer.py
  test/unit/composer/test_history.py
Labels: enhancement, core, composer

#991 Documentation review: typo fixes, improvement suggestions
  docs/source/advanced/index.rst
  docs/source/examples/img_classification_pipelines/class_with_balancing.png
  docs/source/examples/img_classification_pipelines/class_without_balancing.png
  docs/source/examples/img_classification_pipelines/cnn_composite_pipeline.png
  docs/source/examples/img_classification_pipelines/complex_pipeline.png
  docs/source/examples/img_classification_pipelines/complex_rf_pipeline.png
  docs/source/examples/img_classification_pipelines/isolation_forest.png
  docs/source/examples/img_classification_pipelines/manual_three_depth_pipeline.png
  docs/source/examples/img_classification_pipelines/random_forest.png
  docs/source/examples/img_classification_pipelines/svc_complex_pipeline.png
  docs/source/examples/img_regression_pipelines/ransac.png
  docs/source/examples/img_regression_pipelines/three_depth_manual.png
  docs/source/examples/img_ts_pipelines/clstm_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_ar_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_arima_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_complex_dtreg_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_complex_ridge_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_complex_ridge_smoothing_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_ets_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_ets_ridge_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_glm_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_glm_ridge_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_locf_ridge_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_multiple_ets_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_naive_average_ridge_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_polyfit_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_polyfit_ridge_pipeline.png
  docs/source/examples/img_ts_pipelines/ts_stl_arima_pipeline.png
  docs/source/introduction/tutorial/composing_pipelines/automated_creation.rst
  docs/source/introduction/tutorial/composing_pipelines/manual_creation.rst
  docs/source/introduction/tutorial/quickstart.rst
Labels: documentation, discuss
