Repository aimclub/FEDOT, pull requests merged in 2022-02, with the labels that each got.

#555 Cross-validation support for cache
  fedot/core/composer/cache.py
  fedot/core/composer/gp_composer/gp_composer.py
  fedot/core/pipelines/pipeline.py
  fedot/core/validation/compose/metric_estimation.py
  fedot/core/validation/compose/tabular.py
  fedot/core/validation/compose/time_series.py
  fedot/sensitivity/operations_hp_sensitivity/multi_operations_sensitivity.py
  fedot/sensitivity/operations_hp_sensitivity/one_operation_sensitivity.py
  test/unit/composer/test_composer.py
  test/unit/pipelines/test_node_cache.py
  test/unit/preprocessing/test_pipeline_preprocessing.py
  test/unit/preprocessing/test_preprocessors.py
  test/unit/validation/test_table_cv.py
Labels: in progress

#563 Pareto front fix
  examples/advanced/multiobj_optimisation.py
  fedot/api/api_utils/api_composer.py
  fedot/core/composer/gp_composer/gp_composer.py
  fedot/core/optimisers/gp_comp/gp_optimiser.py
  fedot/preprocessing/data_types.py
Labels: bug

#571 Example page added
  docs/source/fedot/benchmarks.rst
  docs/source/fedot/benchmarks/forecasting.rst
  docs/source/fedot/benchmarks/tabular.rst
  docs/source/fedot/img/img_benchmarks/fedot_classregr.png
  docs/source/fedot/img/img_benchmarks/fedot_meta.png
  docs/source/fedot/img/img_benchmarks/fedot_time_series.png
  docs/source/fedot/img/img_benchmarks/ts_metrics.png
  docs/source/fedot/index.rst
Labels: documentation
