Repository aimclub/FEDOT, pull requests merged in 2023-02, with the labels that each got.

#1043 Release 0.6.2
  cases/credit_scoring/credit_scoring_problem.py
  docs/source/conf.py
  examples/advanced/automl/tpot_vs_fedot.py
  examples/advanced/multimodal_text_num_example.py
  examples/advanced/multiobj_optimisation.py
  examples/simple/classification/api_classification.py
  examples/simple/interpretable/api_explain.py
  examples/simple/regression/api_regression.py
  examples/simple/time_series_forecasting/api_forecasting.py
  setup.py
  test/integration/cache/test_parallel_cache_files.py
  test/integration/quality/test_quality_improvement.py
  test/integration/quality/test_synthetic_tasks.py
  test/integration/real_applications/test_examples.py
  test/integration/test_profiler.py
Labels: release

#1049 Remove tests that moved to golem
  examples/advanced/fedot_based_solutions/graph_model_optimization.py
  examples/advanced/profiler_example.py
  examples/data/custom_encoded.csv
  test/integration/automl/test_automl.py
  test/integration/preprocessing/test_pipeline_preprocessing.py
  test/unit/adapter/mock_adapter.py
  test/unit/adapter/test_adapt_pipeline.py
  test/unit/adapter/test_adapt_registry.py
  test/unit/adapter/test_adapt_verification_rules.py
  test/unit/composer/test_builder.py
  test/unit/composer/test_history.py
  test/unit/dag/test_graph.py
  test/unit/dag/test_graph_operator.py
  test/unit/dag/test_node.py
  test/unit/dag/test_unique_list.py
  test/unit/data/test_data_split.py
  test/unit/models/test_repository.py
  test/unit/optimizer/fitness/__init__.py
  test/unit/optimizer/fitness/test_fitness.py
  test/unit/optimizer/gp_operators/test_adapters.py
  test/unit/optimizer/gp_operators/test_crossover.py
  test/unit/optimizer/gp_operators/test_gp_operators.py
  test/unit/optimizer/gp_operators/test_mutation.py
  test/unit/optimizer/test_elitism_operator.py
  test/unit/optimizer/test_generation_keeper.py
  test/unit/optimizer/test_initial_population_generator.py
  test/unit/optimizer/test_iterator.py
  test/unit/optimizer/test_pipeline_objective_eval.py
  test/unit/optimizer/test_selection_operators.py
  test/unit/optimizer/test_tuner_timer.py
  test/unit/pipelines/test_node.py
  test/unit/pipelines/test_pipeline_parameters.py
  test/unit/pipelines/test_pipeline_structure.py
  test/unit/pipelines/test_pipeline_ts_wrappers.py
  test/unit/pipelines/test_pipeline_verification.py
  test/unit/pipelines/tuning/test_pipeline_tuning.py
  test/unit/pipelines/tuning/test_tuner_builder.py
  test/unit/serialization/__init__.py
  test/unit/serialization/conftest.py
  test/unit/serialization/dataclasses/serialization_dataclasses.py
  test/unit/serialization/mocks/__init__.py
  test/unit/serialization/mocks/history_mocks.py
  test/unit/serialization/mocks/serialization_mocks.py
  test/unit/serialization/shared_data.py
  test/unit/serialization/test_custom_serialize.py
  test/unit/serialization/test_decoder.py
  test/unit/serialization/test_encoder.py
  test/unit/serialization/test_get_class.py
  test/unit/serialization/test_object_path_dumping.py
  test/unit/tasks/test_custom.py
  test/unit/test_logger.py
  test/unit/test_utils.py
  test/unit/visualization/__init__.py
  test/unit/visualization/test_composing_history.py
  test/unit/visualization/test_graph_visualizations.py
  test/unit/visualization/test_visualisation_utils.py
Labels: in progress, test

#1048 Docs move for GOLEM before 0.7.0
  docs/source/advanced/adapter.rst
  docs/source/advanced/architecture.rst
  docs/source/advanced/automated_pipelines_design.rst
  docs/source/advanced/img/adapter-structure-v1.png
  docs/source/advanced/index.rst
  docs/source/api/adapter.rst
  docs/source/api/graph.rst
  docs/source/api/graph_node.rst
  docs/source/api/index.rst
  docs/source/api/logging.rst
  docs/source/api/optimizations.rst
  docs/source/api/profiler.rst
Labels: documentation

#1054 Release 070 update
  .github/workflows/manual-build.yml
  .github/workflows/publish_pypi.yml
  .travis.yml
  README.rst
  README_en.rst
  docs/source/conf.py
  other_requirements/extra.txt
  requirements.txt
  setup.py
Labels: release
