Repository aimclub/FEDOT, pull requests merged in 2023-12, with the labels that each got.

#1213 1211-fix
  fedot/core/operations/atomized_model.py
  fedot/core/utils.py
  test/integration/models/test_atomized_model.py
Labels: bug

#1224 Running unit tests manually
  .github/workflows/unit-build.yml
Labels: test

#1215 1182-fix
  fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/naive.py
  fedot/core/repository/data/data_operation_repository.json
  test/integration/models/test_model.py
Labels: test

#1210 Improve the rule for time series pipeline verification
  fedot/core/pipelines/verification.py
  fedot/core/pipelines/verification_rules.py
  fedot/core/repository/data/data_operation_repository.json
  test/unit/pipelines/prediction_intervals/data/pred_ints_model_test.pickle
  test/unit/pipelines/prediction_intervals/data/test_ts.csv
  test/unit/pipelines/prediction_intervals/data/train_ts.csv
  test/unit/pipelines/test_pipeline_verification.py
Labels: core, time series

#1222 1035-docs
  docs/source/introduction/fedot_features/automation_features.rst
  fedot/api/builder.py
  test/integration/models/test_model.py
Labels: documentation
