Repository aimclub/FEDOT, pull requests merged in 2024-05, with the labels that each got.

#1289 Update version of codecov action
  .github/workflows/unit-build.yml
Labels: minor, infrastructure

#1287 Fix gensim for PyPi release
  other_requirements/extra.txt
  requirements.txt
Labels: bug, dependencies

#1292 fix: NaNs containing forecast on some ets configs
  fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
  fedot/core/repository/data/model_repository.json
Labels: bug, time series
