Repository aimclub/FEDOT, pull requests merged in 2024-04, with the labels that each got.

#1280 fix sporadic forecasting test failure
  fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
  fedot/core/pipelines/tuning/search_space.py
  other_requirements/extra.txt
Labels: time series

#1284 add validation on _window_size param in topo extractor
  fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py
  test/unit/data_operations/test_data_operation_params.py
Labels: bug, test

#1286 Intermediate release 0.7.3.2
  fedot/version.py
Labels: release, minor
