Repository aimclub/FEDOT, pull requests merged in 2024-08, with the labels that each got.

#1277 m4 timeseries benchmark
  docs/source/benchmarks/amlb_res.csv
  docs/source/benchmarks/amlb_res.html
  docs/source/benchmarks/forecasting.rst
  docs/source/benchmarks/tabular.rst
Labels: documentation

#1324 fix: do not launch composition for atomized model
  fedot/api/api_utils/predefined_model.py
  fedot/api/main.py
  test/integration/api/test_main_api.py
Labels: bug, api

#1326 Release 0.7.4
  fedot/version.py
Labels: release
