Repository aimclub/FEDOT, pull requests merged in 2024-01, with the labels that each got.

#1237 add window size selector
  fedot/api/api_utils/api_composer.py
  fedot/core/composer/gp_composer/specific_operators.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
  fedot/core/repository/data/default_operation_params.json
  fedot/utilities/window_size_selector.py
  test/unit/data_operations/test_data_operation_params.py
  test/unit/data_operations/test_time_series_operations.py
  test/unit/optimizer/gp_operators/test_mutation.py
  test/unit/utilities/window_size_selector.py
Labels: enhancement, time series

#1242 Hotfix for integration tests
  examples/simple/time_series_forecasting/api_forecasting.py
  fedot/core/repository/data/default_operation_params.json
  test/integration/models/test_model.py
  test/integration/real_applications/test_examples.py
Labels: bug, test

#1226 Improve community standards
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#1225 Add automated code formatter
  .github/workflows/autopep8.yml
  .github/workflows/fix-pep8-command.yml
  .github/workflows/slash-command-dispatch.yml
Labels: enhancement

#1243 Fix readme tests badges
  README.rst
  README_en.rst
Labels: documentation

#1245 Change permission to read for pep8 code formatter
  .github/workflows/slash-command-dispatch.yml
Labels: bug

#1247 Fix code formatter bugs
  .github/workflows/autopep8.yml
  .github/workflows/slash-command-dispatch.yml
Labels: bug

#1252 Fast topological features
  docs/source/introduction/fedot_features/automation_features.rst
  fedot/api/api_utils/assumptions/task_assumptions.py
  fedot/api/builder.py
  fedot/core/operations/evaluation/common_preprocessing.py
  fedot/core/operations/evaluation/operation_implementations/data_operations/topological/fast_topological_extractor.py
  fedot/core/pipelines/tuning/search_space.py
  fedot/core/repository/data/data_operation_repository.json
  fedot/core/repository/data/default_operation_params.json
  test/integration/models/test_model.py
Labels: enhancement, time series
